"""Generate metrics_record_gen.mojo from record_spec.py.

  values_to_rec(values, cache, ts_ns)  worker: flat Python tuple (FIELDS + EXTRA order) -> BatchMetricsRec
  rec_to_values(rec)                   telemetry: BatchMetricsRec -> the same tuple shape
                                       (batch_type as int, completed as a tuple or None)

Run: python3 gen_record_code.py
"""
import os

from record_spec import EXTRA, FIELDS, SUBRECORDS

HERE = os.path.dirname(os.path.abspath(__file__))

READ = {
    "u64": "UInt64(as_int({p}))",
    "f64": "as_f64({p})",
    "bool": "as_bool({p})",
    "batch_type": "cache.batch_type({p})",
    "opt_f64": "as_opt_f64({p})",
    "opt_u64": "as_opt_u64({p})",
    "f64_list": "as_f64_list({p})",
    "u64_list": "as_u64_list({p})",
}
READ.update({k: f"_{k}_from_py({{p}}, cache)" for k, _, _ in SUBRECORDS})

WRITE = {
    "u64": "py_int(Int({v}))",
    "f64": "py_f64({v})",
    "bool": "py_bool({v})",
    "batch_type": "py_int(Int({v}))",
    "opt_f64": "py_opt_f64({v})",
    "opt_u64": "py_opt_u64({v})",
    "f64_list": "py_f64_list({v})",
    "u64_list": "py_u64_list({v})",
}
WRITE.update({k: f"_{k}_to_py({{v}})" for k, _, _ in SUBRECORDS})


def main() -> None:
    all_fields = FIELDS + EXTRA
    L = [
        "# GENERATED by gen_record_code.py from record_spec.py — do not edit.",
        "from std.python import Python, PythonObject",
        "from std.python._cpython import PyObjectPtr",
        "",
        "from pyconv import (ConvCache, as_bool, as_f64, as_f64_list, as_int, as_opt_f64, as_opt_u64,",
        "    as_u64_list, dict_get, is_none, py_bool, py_f64, py_f64_list, py_int, py_opt_f64,",
        "    py_opt_u64, py_tuple, py_u64_list, tuple_item)",
        "from MaxBatchMetricsSink import BatchMetricsRec, " + ", ".join(n for _, n, _ in SUBRECORDS),
        "",
        f"comptime N_VALUES = {len(all_fields)}",
        "",
        "",
        "def subrecord_names() -> List[List[String]]:",
        "    \"\"\"Field names of each sub-record, in record_spec order (ConvCache key objects).\"\"\"",
        "    return [",
    ] + [
        "        [" + ", ".join(f'"{n}"' for n, _ in sub_fields) + "],"
        for _, _, sub_fields in SUBRECORDS
    ] + [
        "    ]",
    ]
    for si, (kind, node, sub_fields) in enumerate(SUBRECORDS):
        L += [
            "",
            "",
            f"def _{kind}_from_py(p: PyObjectPtr, mut cache: ConvCache) raises -> Optional[{node}]:",
            "    if is_none(p):",
            "        return None",
            "    var dict_obj = PythonObject(from_borrowed=p).__dict__",
            "    var d = dict_obj._obj_ptr",
            f"    return Optional({node}(",
        ]
        for i, (name, kind_f) in enumerate(sub_fields):
            L.append(f"        {name}=" + READ[kind_f].format(p=f"dict_get(d, cache.keys[{si}][{i}])") + ",")
        L += [
            "    ))",
            "",
            "",
            f"def _{kind}_to_py(v: Optional[{node}]) raises -> PythonObject:",
            "    if not v:",
            "        return Python.none()",
            "    ref c = v.value()",
            f"    var items = List[PythonObject](capacity={len(sub_fields)})",
        ]
        for name, kind_f in sub_fields:
            L.append("    items.append(" + WRITE[kind_f].format(v=f"c.{name}") + ")")
        L += ["    return py_tuple(items^)"]
    L += [
        "",
        "",
        "def values_to_rec(values: PythonObject, mut cache: ConvCache, ts_ns: UInt64) raises -> BatchMetricsRec:",
        "    var t = values._obj_ptr",
        "    return BatchMetricsRec(",
        "        ts_ns=ts_ns,",
    ]
    for i, (name, kind) in enumerate(all_fields):
        L.append(f"        {name}=" + READ[kind].format(p=f"tuple_item(t, {i})") + ",")
    L += [
        "    )",
        "",
        "",
        "def rec_to_values(r: BatchMetricsRec) raises -> PythonObject:",
        "    var items = List[PythonObject](capacity=N_VALUES)",
    ]
    for name, kind in all_fields:
        L.append("    items.append(" + WRITE[kind].format(v=f"r.{name}") + ")")
    L += ["    return py_tuple(items^)", ""]
    path = os.path.join(HERE, "metrics_record_gen.mojo")
    with open(path, "w") as fh:
        fh.write("\n".join(L))
    subs = ", ".join(f"{k} {len(f)}" for k, _, f in SUBRECORDS)
    print(f"wrote {path} ({len(all_fields)} values; sub-records: {subs})")


if __name__ == "__main__":
    main()
